name: Daily Dev Meme

on:
  schedule:
    - cron: "0 5 * * *" # runs daily at 05:00 UTC
  workflow_dispatch:

jobs:
  update-meme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Meme from Reddit (images only)
        run: |
          MEME_URL=""
          # Keep looping until we get a JPG or PNG
          for i in {1..5}; do
            URL=$(curl -s https://www.reddit.com/r/ProgrammerHumor/random/.json \
              | jq -r '.[0].data.children[0].data.url_overridden_by_dest')
            if [[ "$URL" == *.jpg || "$URL" == *.png ]]; then
              MEME_URL=$URL
              break
            fi
          done
          echo $MEME_URL > meme.txt

      - name: Update README
        run: |
          MEME_URL=$(cat meme.txt)
          if [ -n "$MEME_URL" ]; then
            sed -i "/<!--START_SECTION:devmeme-->/, /<!--END_SECTION:devmeme-->/c\<!--START_SECTION:devmeme-->\n![Meme](${MEME_URL})\n<!--END_SECTION:devmeme-->" README.md
          fi

      - name: Commit & Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "chore: update daily dev meme" || echo "No new meme today"
          git push
